Repository reMRKableDev/dubsterdam-page, pull requests merged in 2020-10, with the labels that each got.

#86 Stable Develop build
  README.md
  package-lock.json
  package.json
  src/components/Footer/Footer.js
  src/components/Footer/__snapshots__/Footer.test.js.snap
  src/components/Navigation/Navbar.js
  src/components/Navigation/__snapshots__/Navbar.test.js.snap
  src/components/NotFoundPage/NotFound.test.js
  src/components/Root/App.js
  src/components/Root/App.test.js
  src/helpers/randomGreeting.js
Labels: enhancement

#87 Stable build
  src/components/NotFoundPage/NotFound.test.js
Labels: dependencies

#88 Update title and content description in headUpdate title and content description in head
  public/index.html
Labels: hacktoberfest-accepted

#89 Stable develop build
  src/components/Navigation/Navbar.js
  src/components/Navigation/Navbar.test.js
  src/components/Navigation/NavbarButton.js
  src/components/Navigation/NavbarButton.test.js
  src/components/Navigation/__snapshots__/Navbar.test.js.snap
Labels: enhancement
